version: '2'
services:
  dbms:
    build: 
        context: .
        dockerfile: database/Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
  svnrepo:
    container_name: svnrepo
    image: docker.wso2.com/svnrepo
  esb-analytics:
    container_name: esb-analytics
    build:
      context: .
      dockerfile: esb-analytics/Dockerfile
    environment:
      - SLEEP=5
  esb_manager:
    container_name: esb_manager
    depends_on: 
      - dbms
    build:
      context: .
      dockerfile: esb-manager/Dockerfile
    environment:
      - SLEEP=60
    links:
      - nginx:esb.wso2.org
      - nginx:mgt.esb.wso2.org
  esb_worker1:
    container_name: esb_worker1
    depends_on:
      - dbms
      - esb_manager
      - esb-analytics
    build:
      context: .
      dockerfile: esb-worker1/Dockerfile
    environment:
      - SLEEP=100
    links:
      - nginx:esb.wso2.org
      - nginx:mgt.esb.wso2.org
  esb_worker2:
    container_name: esb_worker2
    depends_on:
      - dbms
      - esb_manager
      - esb-analytics
    links:
      - nginx:esb.wso2.org
      - nginx:mgt.esb.wso2.org
    build:
      context: .
      dockerfile: esb-worker2/Dockerfile
    environment:
      - SLEEP=150
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    environment:
      - SLEEP=30
    ports:
      - "443:443"
      - "80:80"
      - "9444:9444"

